jiraBaseURL: https://gh2jiratest.atlassian.net/
project: GT

daysUntilStale: 180
daysUntilClose: 90

exemptLabels:
  - lifecycle-frozen

staleLabel: lifecycle-stale
closeStatus: Closed
limitPerRun: 100
